#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 *
 * This file has been heavily edited by JumpyJacko, mainly for looks and ease of use
 */

/* Defining Homerow Mods for Readability */
#define HOME_A LGUI_T(KC_A)
#define HOME_R LALT_T(KC_R)
#define HOME_S LSFT_T(KC_S)
#define HOME_T LCTL_T(KC_T)

#define HOME_N RCTL_T(KC_N)
#define HOME_E RSFT_T(KC_E)
#define HOME_I RALT_T(KC_I)
#define HOME_O RGUI_T(KC_O)


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(   KC_Q,   KC_W,   KC_F,   KC_P,   KC_B,   KC_J,   KC_L,   KC_U,     KC_Y,    KC_SCLN, 
                    HOME_A, HOME_R, HOME_S, HOME_T, KC_G,   KC_M,   HOME_N, HOME_E,   HOME_I,  HOME_O, 
                    KC_Z,   KC_X,   KC_C,   KC_D,   KC_V,   KC_K,   KC_H,   KC_COMM,  KC_DOT,  KC_SLSH, 
                                    LT(1,KC_ENT), KC_BSPC,  KC_SPC, LT(2,KC_TAB)
                ),
                        /* Colemak-dh Layer
                        *
                        * ,-----------------------------.        ,-----------------------------.
                        * |  q  |  w  |  f  |  p  |  b  |        |  j  |  l  |  u  |  y  |  ;  |
                        * |-----+-----+-----+-----+-----|        |-----+-----+-----+-----+-----|
                        * |  a  |  r  |  s  |  t  |  g  |        |  m  |  n  |  e  |  i  |  o  |
                        * |-----+-----+-----+-----+-----|        |-----+-----+-----+-----+-----|
                        * |  z  |  x  |  c  |  d  |  v  |        |  k  |  h  |  ,  |  .  |  /  |
                        * `-----------------------------|        |-----------------------------'
                        *                   | ent |bkspc|        | spc | tab |
                        *                   '-----------'        '-----------'
                        */
    [1] = LAYOUT(   KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0, 
                    KC_DLR,  KC_PLUS, KC_LPRN, KC_RPRN, KC_AT,   KC_PIPE, KC_MINS, KC_EQL,  KC_UNDS, KC_ASTR, 
                    KC_EXLM, KC_HASH, KC_LCBR, KC_RCBR, KC_TILD, KC_AMPR, KC_LBRC, KC_RBRC, KC_PERC, KC_CIRC,
                                                    KC_NO, KC_BSPC, KC_SPC, KC_TAB
                ),
                        /* Numbers and Symbols Layer (Basically Stolen from winternebs)
                        *
                        * ,-----------------------------.        ,-----------------------------.
                        * |  1  |  2  |  3  |  4  |  5  |        |  6  |  7  |  8  |  9  |  0  |
                        * |-----+-----+-----+-----+-----|        |-----+-----+-----+-----+-----|
                        * |  $  |  +  |  (  |  )  |  @  |        |  |  |  -  |  =  |  _  |  *  |
                        * |-----+-----+-----+-----+-----|        |-----+-----+-----+-----+-----|
                        * |  !  |  #  |  {  |  }  |  ~  |        |  &  |  [  |  ]  |  %  |  ^  |
                        * `-----------------------------|        |-----------------------------'
                        *                   | xxx |bkspc|        | spc | tab |
                        *                   '-----------'        '-----------'
                        */
    [2] = LAYOUT(   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_9,    KC_F10, 
                    KC_MS_L, KC_MS_U, KC_MS_D, KC_MS_R, KC_F11,  KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, KC_F12, 
                    KC_MUTE, KC_VOLD, KC_VOLU, DF(0),   DF(3),   KC_MFFD, KC_MPLY, KC_MSTP, KC_MRWD, KC_MS_L, 
                                                KC_ENT, KC_BSPC,  KC_SPC, KC_NO
                ),
                        /* Fn, Nav, and Media Layer + Layer Activation Keys for Regular and Gaming Use
                        *
                        * ,-----------------------------.        ,-----------------------------.
                        * | Fn1 | Fn2 | Fn3 | Fn4 | Fn5 |        | Fn6 | Fn7 | Fn8 | Fn9 | F10 |
                        * |-----+-----+-----+-----+-----|        |-----+-----+-----+-----+-----|
                        * | MSL | MSU | MSD | MSR | F11 |        |Left |Down | Up  |Right| F12 |
                        * |-----+-----+-----+-----+-----|        |-----+-----+-----+-----+-----|
                        * |Mute |VolDn|VolUp|Layr0|Layr3|        |Medi>|MediP|MediS|Medi<|CilkL|
                        * `-----------------------------|        |-----------------------------'
                        *                   | ent |bkspc|        | spc | xxx |
                        *                   '-----------'        '-----------'
                        */
    [3] = LAYOUT(   KC_ESC,  KC_Q,  KC_W,   KC_E,   KC_R,   KC_T,   KC_Y,   KC_U,   KC_I,   KC_O, 
                    KC_LSFT, KC_A,  KC_S,   KC_D,   KC_F,   KC_G,   KC_H,   KC_J,   KC_K,   KC_L, 
                    KC_LCTL, KC_Z,  KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M,   KC_P,   KC_LALT, 
                                    KC_TAB, KC_SPC, KC_BSPC, LT(2,KC_ENT)
                )
                        /* Gaming Layer
                        *
                        * ,-----------------------------.        ,-----------------------------.
                        * | Esc |  q  |  w  |  e  |  r  |        |  t  |  y  |  i  |  u  |  o  |
                        * |-----+-----+-----+-----+-----|        |-----+-----+-----+-----+-----|
                        * |Shift|  a  |  s  |  d  |  f  |        |  g  |  h  |  j  |  k  |  l  |
                        * |-----+-----+-----+-----+-----|        |-----+-----+-----+-----+-----|
                        * |LCtrl|  z  |  x  |  c  |  v  |        |  b  |  n  |  m  |  p  |LfAlt|
                        * `-----------------------------|        |-----------------------------'
                        *                   | tab | spc |        |bkspc| ent |
                        *                   '-----------'        '-----------'
                        */
};